package modelo;
// Generated 2/04/2019 12:57:22 AM by Hibernate Tools 4.3.1



/**
 * Grupo generated by hbm2java
 */
public class Grupo  implements java.io.Serializable {


     private String cveGru;
     private String nomGru;

    public Grupo() {
    }

    public Grupo(String cveGru, String nomGru) {
       this.cveGru = cveGru;
       this.nomGru = nomGru;
    }
   
    public String getCveGru() {
        return this.cveGru;
    }
    
    public void setCveGru(String cveGru) {
        this.cveGru = cveGru;
    }
    public String getNomGru() {
        return this.nomGru;
    }
    
    public void setNomGru(String nomGru) {
        this.nomGru = nomGru;
    }




}


